version: '3'
services: 
  flask:
    build: app/
    container_name: flask
    image: ubuntu:latest
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: Dibilingo
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: our_really_hard_pass
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: our_really_hard_pass
      MONGO_INITDB_DATABASE: Dibilingo
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:  #change before prod
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
      - frontend # change before prod

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local